In [1]:
import os
import numpy as np
import h5py
from DatasetCreation import DatasetCreation

In [2]:
path_hdf5 = '/media/philipp/DATA/dataset/dataset_256_df_177.h5'
hdf5_ds = h5py.File(path_hdf5, 'r')

In [3]:
hdf5_ds['dsm']

<HDF5 dataset "dsm": shape (42716, 256, 256, 1), type "<f2">

In [2]:
path_load = '/home/philipp/Data/edin_index/train_indices.npy'
train = np.sort(np.load(path_load))

path_load = '/home/philipp/Data/edin_index/val_indices.npy'
val = np.sort(np.load(path_load))

path_load = '/home/philipp/Data/edin_index/test_indices.npy'
test = np.sort(np.load(path_load))

In [3]:
train

array([    0,     1,     2, ..., 42713, 42714, 42715])

In [4]:
val

array([    7,    14,    17, ..., 42697, 42707, 42710])

In [5]:
idx = np.sort(np.concatenate((train, val)))

In [6]:
idx

array([    0,     1,     2, ..., 42713, 42714, 42715])

In [7]:
print(train.shape)
print(val.shape)
print(test.shape)

(29908,)
(4268,)
(8540,)


In [46]:
29908+4268

34176

In [35]:
train[25000:25100]

array([33001, 33002, 33003, 33004, 33005, 33007, 33010, 33011, 33013,
       33014, 33015, 33016, 33017, 33018, 33019, 33020, 33023, 33024,
       33026, 33027, 33029, 33030, 33031, 33032, 33034, 33035, 33036,
       33038, 33039, 33040, 33043, 33046, 33050, 33052, 33053, 33054,
       33055, 33056, 33057, 33062, 33063, 33065, 33067, 33068, 33073,
       33074, 33075, 33076, 33077, 33078, 33079, 33080, 33081, 33082,
       33084, 33085, 33086, 33087, 33088, 33089, 33090, 33093, 33094,
       33095, 33096, 33097, 33098, 33099, 33101, 33103, 33104, 33106,
       33110, 33111, 33112, 33115, 33116, 33117, 33118, 33119, 33120,
       33121, 33123, 33124, 33126, 33128, 33129, 33131, 33132, 33133,
       33136, 33139, 33140, 33141, 33142, 33143, 33144, 33145, 33146,
       33148])

In [32]:
hdf5_ds['dsm'][40000:40100].shape

(100, 256, 256, 1)

In [42]:
hdf5_ds['dsm'][train[25000:26000]].shape

(1000, 256, 256, 1)

In [28]:
hdf5_ds['dsm'][x[10000:20000]].shape

TypeError: Indexing elements must be in increasing order

In [44]:
train.close()

AttributeError: 'numpy.ndarray' object has no attribute 'close'

In [45]:
hdf5_ds.close()

In [43]:
#####################################################################################

In [44]:
# create dataset

In [53]:
def create_hdf5(path_file, tile_size, dataset_size):
    path_hdf5 = path_file
    # cerate file
    hdf5_ds = h5py.File(path_file, 'a')
    # create dataset
    for data_type in data_types:
        x = hdf5_ds.create_dataset(data_type, \
        (dataset_size, tile_size, tile_size, data_dic[data_type]['dim']), \
        dtype=data_dic[data_type]['dtype'])
    hdf5_ds.close()

In [7]:
type_mask='ground_truth_std'
data_dic = {'ortho':{'dtype':np.uint8, 'dim':4}, \
            'dsm':{'dtype':np.float16, 'dim':1}, \
            'dtm':{'dtype':np.float16, 'dim':1}, \
            'slope':{'dtype':np.float16, 'dim':1}, \
            'age':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_std':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac12':{'dtype':np.uint8, 'dim':1}, \
            'ground_truth_ac1':{'dtype':np.uint8, 'dim':1}}

data_types = list(data_dic.keys())

In [8]:
# set output path
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'

if not os.path.isfile(path_hdf5):
    print('file not found -> creating file')
    # create new hdf5 file
    create_hdf5(path_hdf5, tile_size=256, dataset_size=10679*4+34176) # tams: 39280, bisch: 35272
else:
    print('file existing')

file existing


In [56]:
#######################################################################################
# feed data

In [9]:
# set output path
path_main = '/media/philipp/DATA/dataset/dataset_256_df_177.h5'
# load data
main_ds = h5py.File(path_main, 'r')

In [10]:
# set output path
path_hdf5 = '/media/philipp/DATA/dataset/dataset_ext_256_df_177.h5'
# load data
hdf5_ds = h5py.File(path_hdf5, 'a')

In [11]:
main_ds['ortho']

<HDF5 dataset "ortho": shape (42716, 256, 256, 4), type "|u1">

In [12]:
hdf5_ds['ortho']

<HDF5 dataset "ortho": shape (76892, 256, 256, 4), type "|u1">

In [15]:
# copy original
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[5000:42716,:,:,:] = source[5000:42716,:,:,:]

In [27]:
# copy fliped
for data_type in data_types:
    # set dataset
    source = main_ds[data_type]
    # set dataset
    target = hdf5_ds[data_type]
    # assign data
    target[idx[42716+30000:42716+34176],:,:,:] = np.flip(source[30000:34176,:,:,:], axis=2)

In [28]:
hdf5_ds.close()
main_ds.close()

In [ ]:
#######################################################################################